language: ruby

# we run 1.9.3 but heroku runs 1.9.2
rvm:
  - 1.9.3
  - 1.9.2

env: DB=sqlite

before_script:
  - bundle exec rake db:migrate db:test:prepare db:seed

script: RAILS_ENV=test bundle exec rspec spec

# avoid pg
bundler_args: --without production

# build for branches:
branches:
  only:
    - master
    - development
